version: 2

sources:
  - name: chicago_taxi
    database: bigquery-public-data
    schema: chicago_taxi_trips
    tables:
      - name: taxi_trips

  - name: taxi_raw
    database: astrafy-de-proj
    schema: taxi_raw
    tables:
      - name: weather_daily