taxi_dbt:
  target: ci
  outputs:
    ci:
      dataset: taxi_raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: astrafy-de-proj
      threads: 4
      type: bigquery
