name: dbt

on:
  push:
    branches: [ "main" ]
    paths:
      - 'taxi_dbt/**'
  pull_request:
    paths:
      - 'taxi_dbt/**'

jobs:
  dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: taxi_dbt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-bigquery
        run: pip install dbt-bigquery==1.8.*

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DBT_GCP_SA_KEY }}

      - name: Write dbt SA key
        run: |
          echo '${{ secrets.DBT_GCP_SA_KEY }}' > $HOME/dbt-sa.json

      - name: Create profiles.yml for CI
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << 'YAML'
          taxi_dbt:
            target: ci
            outputs:
              ci:
                type: bigquery
                method: service-account
                keyfile: /home/runner/dbt-sa.json
                project: ${{ secrets.DBT_GCP_PROJECT_ID }}
                dataset: taxi_raw
                location: EU
                threads: 4
          YAML

      - name: dbt debug
        run: dbt debug

      - name: dbt build
        run: dbt build
