name: Terraform

on:
  pull_request:
    paths:
      - 'terraform/**'
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud (for provider auth)
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_project_id }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
          TF_VAR_bq_dataset_id: ${{ secrets.TF_VAR_bq_dataset_id }}
          TF_VAR_bq_location: ${{ secrets.TF_VAR_bq_location }}
          TF_VAR_gcs_bucket_name: ${{ secrets.TF_VAR_gcs_bucket_name }}
          TF_VAR_gcs_location: ${{ secrets.TF_VAR_gcs_location }}
          TF_VAR_gcs_versioning: ${{ secrets.TF_VAR_gcs_versioning }}

      - name: Terraform Apply (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_project_id: ${{ secrets.TF_VAR_project_id }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
          TF_VAR_bq_dataset_id: ${{ secrets.TF_VAR_bq_dataset_id }}
          TF_VAR_bq_location: ${{ secrets.TF_VAR_bq_location }}
          TF_VAR_gcs_bucket_name: ${{ secrets.TF_VAR_gcs_bucket_name }}
          TF_VAR_gcs_location: ${{ secrets.TF_VAR_gcs_location }}
          TF_VAR_gcs_versioning: ${{ secrets.TF_VAR_gcs_versioning }}
